# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: main.yml
telemetry_vars:
  - "{{ role_path }}/../../../prepare_oim/roles/deploy_containers/idrac_telemetry/vars/main.yml"
  - "{{ role_path }}/../../../prepare_oim/roles/deploy_containers/prometheus/vars/main.yml"
  - "{{ role_path }}/../../../prepare_oim/roles/deploy_containers/grafana/vars/main.yml"
  - "{{ role_path }}/../../../prepare_oim/roles/deploy_containers/loki/vars/main.yml"
  - "{{ role_path }}/../../../prepare_oim/roles/deploy_containers/common/vars/main.yml"
oim_shared_path: "{{ hostvars['localhost']['oim_shared_path'] }}"
