# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Parse forced conf file from localhost
  slurm_conf:
    op: parse
    conf_name: "{{ forced_conf }}"
    path: "{{ configs_input[forced_conf] }}"
  delegate_to: localhost
  register: forced_conf_parsed
  no_log: true
  when:
    - configs_input[forced_conf] is string

- name: Use forced conf dict directly
  ansible.builtin.set_fact:
    forced_conf_dict: "{{ configs_input[forced_conf] }}"
  no_log: true
  when:
    - configs_input[forced_conf] is mapping

- name: Use parsed forced conf dict
  ansible.builtin.set_fact:
    forced_conf_dict: "{{ forced_conf_parsed.conf_dict }}"
  no_log: true
  when:
    - configs_input[forced_conf] is string
    - forced_conf_parsed is success

- name: Convert forced conf to ini format
  slurm_conf:
    op: merge
    conf_sources: "{{ [forced_conf_dict] }}"
    conf_name: "{{ forced_conf }}"
  register: forced_conf_result
  delegate_to: localhost
  no_log: true
  when:
    - forced_conf_dict is defined

- name: Write forced .conf file as-is
  ansible.builtin.copy:
    content: "{{ forced_conf_result.ini_lines | join('\n') }}\n"
    dest: "{{ slurm_config_path }}/{{ ctld_list[0] }}/etc/slurm/{{ forced_conf }}.conf"
    mode: "0640"
    owner: "{{ slurm_user }}"
    group: "{{ slurm_user_group }}"
    remote_src: "{{ copy_from_oim }}"
  register: forced_conf_written
  no_log: true
  when:
    - forced_conf_result is defined
    - forced_conf_result.ini_lines is defined
